# Generated by Django 5.1.4 on 2025-01-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='founder',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='frameworks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
